// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameProtobufs.Services {

  /// <summary>Holder for reflection information generated from Service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for Service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1TZXJ2aWNlLnByb3RvEhZHYW1lUHJvdG9idWZzLlNlcnZpY2VzGgtTdGF0",
            "ZS5wcm90byIgCgtKb2luUmVxdWVzdBIRCgl0aW1lc3RhbXAYASABKAUiIQoM",
            "Sm9pblJlc3BvbnNlEhEKCXRpbWVzdGFtcBgBIAEoBSIOCgxMZWF2ZVJlcXVl",
            "c3QiDwoNTGVhdmVSZXNwb25zZSIiCg1VcGRhdGVSZXF1ZXN0EhEKCXRpbWVz",
            "dGFtcBgBIAEoBSI8Cg5VcGRhdGVSZXNwb25zZRIqCgVzdGF0ZRgBIAEoCzIb",
            "LkdhbWVQcm90b2J1ZnMuU3RhdGVNZXNzYWdlIv8BCg5SZXF1ZXN0TWVzc2Fn",
            "ZRI5CgtzZXJ2aWNlVHlwZRgBIAEoDjIkLkdhbWVQcm90b2J1ZnMuU2Vydmlj",
            "ZXMuU2VydmljZVR5cGVzEjgKC2pvaW5SZXF1ZXN0GAIgASgLMiMuR2FtZVBy",
            "b3RvYnVmcy5TZXJ2aWNlcy5Kb2luUmVxdWVzdBI6CgxsZWF2ZVJlcXVlc3QY",
            "AyABKAsyJC5HYW1lUHJvdG9idWZzLlNlcnZpY2VzLkxlYXZlUmVxdWVzdBI8",
            "Cg11cGRhdGVSZXF1ZXN0GAQgASgLMiUuR2FtZVByb3RvYnVmcy5TZXJ2aWNl",
            "cy5VcGRhdGVSZXF1ZXN0IoYCCg9SZXNwb25zZU1lc3NhZ2USOQoLc2Vydmlj",
            "ZVR5cGUYASABKA4yJC5HYW1lUHJvdG9idWZzLlNlcnZpY2VzLlNlcnZpY2VU",
            "eXBlcxI6Cgxqb2luUmVzcG9uc2UYAiABKAsyJC5HYW1lUHJvdG9idWZzLlNl",
            "cnZpY2VzLkpvaW5SZXNwb25zZRI8Cg1sZWF2ZVJlc3BvbnNlGAMgASgLMiUu",
            "R2FtZVByb3RvYnVmcy5TZXJ2aWNlcy5MZWF2ZVJlc3BvbnNlEj4KDnVwZGF0",
            "ZVJlc3BvbnNlGAQgASgLMiYuR2FtZVByb3RvYnVmcy5TZXJ2aWNlcy5VcGRh",
            "dGVSZXNwb25zZSo5CgxTZXJ2aWNlVHlwZXMSCAoETnVsbBAAEggKBEpvaW4Q",
            "ARIJCgVMZWF2ZRACEgoKBlVwZGF0ZRADYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::GameProtobufs.StateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameProtobufs.Services.ServiceTypes), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProtobufs.Services.JoinRequest), global::GameProtobufs.Services.JoinRequest.Parser, new[]{ "Timestamp" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProtobufs.Services.JoinResponse), global::GameProtobufs.Services.JoinResponse.Parser, new[]{ "Timestamp" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProtobufs.Services.LeaveRequest), global::GameProtobufs.Services.LeaveRequest.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProtobufs.Services.LeaveResponse), global::GameProtobufs.Services.LeaveResponse.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProtobufs.Services.UpdateRequest), global::GameProtobufs.Services.UpdateRequest.Parser, new[]{ "Timestamp" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProtobufs.Services.UpdateResponse), global::GameProtobufs.Services.UpdateResponse.Parser, new[]{ "State" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProtobufs.Services.RequestMessage), global::GameProtobufs.Services.RequestMessage.Parser, new[]{ "ServiceType", "JoinRequest", "LeaveRequest", "UpdateRequest" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProtobufs.Services.ResponseMessage), global::GameProtobufs.Services.ResponseMessage.Parser, new[]{ "ServiceType", "JoinResponse", "LeaveResponse", "UpdateResponse" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ServiceTypes {
    [pbr::OriginalName("Null")] Null = 0,
    [pbr::OriginalName("Join")] Join = 1,
    [pbr::OriginalName("Leave")] Leave = 2,
    [pbr::OriginalName("Update")] Update = 3,
  }

  #endregion

  #region Messages
  public sealed partial class JoinRequest : pb::IMessage<JoinRequest> {
    private static readonly pb::MessageParser<JoinRequest> _parser = new pb::MessageParser<JoinRequest>(() => new JoinRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<JoinRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProtobufs.Services.ServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinRequest(JoinRequest other) : this() {
      timestamp_ = other.timestamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinRequest Clone() {
      return new JoinRequest(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private int timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as JoinRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(JoinRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timestamp != other.Timestamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Timestamp != 0) hash ^= Timestamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Timestamp != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Timestamp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Timestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(JoinRequest other) {
      if (other == null) {
        return;
      }
      if (other.Timestamp != 0) {
        Timestamp = other.Timestamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Timestamp = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class JoinResponse : pb::IMessage<JoinResponse> {
    private static readonly pb::MessageParser<JoinResponse> _parser = new pb::MessageParser<JoinResponse>(() => new JoinResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<JoinResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProtobufs.Services.ServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinResponse(JoinResponse other) : this() {
      timestamp_ = other.timestamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public JoinResponse Clone() {
      return new JoinResponse(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private int timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as JoinResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(JoinResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timestamp != other.Timestamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Timestamp != 0) hash ^= Timestamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Timestamp != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Timestamp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Timestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(JoinResponse other) {
      if (other == null) {
        return;
      }
      if (other.Timestamp != 0) {
        Timestamp = other.Timestamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Timestamp = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class LeaveRequest : pb::IMessage<LeaveRequest> {
    private static readonly pb::MessageParser<LeaveRequest> _parser = new pb::MessageParser<LeaveRequest>(() => new LeaveRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LeaveRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProtobufs.Services.ServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaveRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaveRequest(LeaveRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaveRequest Clone() {
      return new LeaveRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LeaveRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LeaveRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LeaveRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class LeaveResponse : pb::IMessage<LeaveResponse> {
    private static readonly pb::MessageParser<LeaveResponse> _parser = new pb::MessageParser<LeaveResponse>(() => new LeaveResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LeaveResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProtobufs.Services.ServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaveResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaveResponse(LeaveResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LeaveResponse Clone() {
      return new LeaveResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LeaveResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LeaveResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LeaveResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class UpdateRequest : pb::IMessage<UpdateRequest> {
    private static readonly pb::MessageParser<UpdateRequest> _parser = new pb::MessageParser<UpdateRequest>(() => new UpdateRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProtobufs.Services.ServiceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateRequest(UpdateRequest other) : this() {
      timestamp_ = other.timestamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateRequest Clone() {
      return new UpdateRequest(this);
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private int timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Timestamp != other.Timestamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Timestamp != 0) hash ^= Timestamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Timestamp != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Timestamp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Timestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateRequest other) {
      if (other == null) {
        return;
      }
      if (other.Timestamp != 0) {
        Timestamp = other.Timestamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Timestamp = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class UpdateResponse : pb::IMessage<UpdateResponse> {
    private static readonly pb::MessageParser<UpdateResponse> _parser = new pb::MessageParser<UpdateResponse>(() => new UpdateResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProtobufs.Services.ServiceReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateResponse(UpdateResponse other) : this() {
      state_ = other.state_ != null ? other.state_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateResponse Clone() {
      return new UpdateResponse(this);
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 1;
    private global::GameProtobufs.StateMessage state_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtobufs.StateMessage State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(State, other.State)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (state_ != null) hash ^= State.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (state_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (state_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(State);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateResponse other) {
      if (other == null) {
        return;
      }
      if (other.state_ != null) {
        if (state_ == null) {
          State = new global::GameProtobufs.StateMessage();
        }
        State.MergeFrom(other.State);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (state_ == null) {
              State = new global::GameProtobufs.StateMessage();
            }
            input.ReadMessage(State);
            break;
          }
        }
      }
    }

  }

  public sealed partial class RequestMessage : pb::IMessage<RequestMessage> {
    private static readonly pb::MessageParser<RequestMessage> _parser = new pb::MessageParser<RequestMessage>(() => new RequestMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RequestMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProtobufs.Services.ServiceReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestMessage(RequestMessage other) : this() {
      serviceType_ = other.serviceType_;
      joinRequest_ = other.joinRequest_ != null ? other.joinRequest_.Clone() : null;
      leaveRequest_ = other.leaveRequest_ != null ? other.leaveRequest_.Clone() : null;
      updateRequest_ = other.updateRequest_ != null ? other.updateRequest_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestMessage Clone() {
      return new RequestMessage(this);
    }

    /// <summary>Field number for the "serviceType" field.</summary>
    public const int ServiceTypeFieldNumber = 1;
    private global::GameProtobufs.Services.ServiceTypes serviceType_ = global::GameProtobufs.Services.ServiceTypes.Null;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtobufs.Services.ServiceTypes ServiceType {
      get { return serviceType_; }
      set {
        serviceType_ = value;
      }
    }

    /// <summary>Field number for the "joinRequest" field.</summary>
    public const int JoinRequestFieldNumber = 2;
    private global::GameProtobufs.Services.JoinRequest joinRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtobufs.Services.JoinRequest JoinRequest {
      get { return joinRequest_; }
      set {
        joinRequest_ = value;
      }
    }

    /// <summary>Field number for the "leaveRequest" field.</summary>
    public const int LeaveRequestFieldNumber = 3;
    private global::GameProtobufs.Services.LeaveRequest leaveRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtobufs.Services.LeaveRequest LeaveRequest {
      get { return leaveRequest_; }
      set {
        leaveRequest_ = value;
      }
    }

    /// <summary>Field number for the "updateRequest" field.</summary>
    public const int UpdateRequestFieldNumber = 4;
    private global::GameProtobufs.Services.UpdateRequest updateRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtobufs.Services.UpdateRequest UpdateRequest {
      get { return updateRequest_; }
      set {
        updateRequest_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RequestMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RequestMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ServiceType != other.ServiceType) return false;
      if (!object.Equals(JoinRequest, other.JoinRequest)) return false;
      if (!object.Equals(LeaveRequest, other.LeaveRequest)) return false;
      if (!object.Equals(UpdateRequest, other.UpdateRequest)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ServiceType != global::GameProtobufs.Services.ServiceTypes.Null) hash ^= ServiceType.GetHashCode();
      if (joinRequest_ != null) hash ^= JoinRequest.GetHashCode();
      if (leaveRequest_ != null) hash ^= LeaveRequest.GetHashCode();
      if (updateRequest_ != null) hash ^= UpdateRequest.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ServiceType != global::GameProtobufs.Services.ServiceTypes.Null) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ServiceType);
      }
      if (joinRequest_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(JoinRequest);
      }
      if (leaveRequest_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(LeaveRequest);
      }
      if (updateRequest_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(UpdateRequest);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ServiceType != global::GameProtobufs.Services.ServiceTypes.Null) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ServiceType);
      }
      if (joinRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(JoinRequest);
      }
      if (leaveRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LeaveRequest);
      }
      if (updateRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdateRequest);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RequestMessage other) {
      if (other == null) {
        return;
      }
      if (other.ServiceType != global::GameProtobufs.Services.ServiceTypes.Null) {
        ServiceType = other.ServiceType;
      }
      if (other.joinRequest_ != null) {
        if (joinRequest_ == null) {
          JoinRequest = new global::GameProtobufs.Services.JoinRequest();
        }
        JoinRequest.MergeFrom(other.JoinRequest);
      }
      if (other.leaveRequest_ != null) {
        if (leaveRequest_ == null) {
          LeaveRequest = new global::GameProtobufs.Services.LeaveRequest();
        }
        LeaveRequest.MergeFrom(other.LeaveRequest);
      }
      if (other.updateRequest_ != null) {
        if (updateRequest_ == null) {
          UpdateRequest = new global::GameProtobufs.Services.UpdateRequest();
        }
        UpdateRequest.MergeFrom(other.UpdateRequest);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ServiceType = (global::GameProtobufs.Services.ServiceTypes) input.ReadEnum();
            break;
          }
          case 18: {
            if (joinRequest_ == null) {
              JoinRequest = new global::GameProtobufs.Services.JoinRequest();
            }
            input.ReadMessage(JoinRequest);
            break;
          }
          case 26: {
            if (leaveRequest_ == null) {
              LeaveRequest = new global::GameProtobufs.Services.LeaveRequest();
            }
            input.ReadMessage(LeaveRequest);
            break;
          }
          case 34: {
            if (updateRequest_ == null) {
              UpdateRequest = new global::GameProtobufs.Services.UpdateRequest();
            }
            input.ReadMessage(UpdateRequest);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ResponseMessage : pb::IMessage<ResponseMessage> {
    private static readonly pb::MessageParser<ResponseMessage> _parser = new pb::MessageParser<ResponseMessage>(() => new ResponseMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResponseMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProtobufs.Services.ServiceReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseMessage(ResponseMessage other) : this() {
      serviceType_ = other.serviceType_;
      joinResponse_ = other.joinResponse_ != null ? other.joinResponse_.Clone() : null;
      leaveResponse_ = other.leaveResponse_ != null ? other.leaveResponse_.Clone() : null;
      updateResponse_ = other.updateResponse_ != null ? other.updateResponse_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResponseMessage Clone() {
      return new ResponseMessage(this);
    }

    /// <summary>Field number for the "serviceType" field.</summary>
    public const int ServiceTypeFieldNumber = 1;
    private global::GameProtobufs.Services.ServiceTypes serviceType_ = global::GameProtobufs.Services.ServiceTypes.Null;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtobufs.Services.ServiceTypes ServiceType {
      get { return serviceType_; }
      set {
        serviceType_ = value;
      }
    }

    /// <summary>Field number for the "joinResponse" field.</summary>
    public const int JoinResponseFieldNumber = 2;
    private global::GameProtobufs.Services.JoinResponse joinResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtobufs.Services.JoinResponse JoinResponse {
      get { return joinResponse_; }
      set {
        joinResponse_ = value;
      }
    }

    /// <summary>Field number for the "leaveResponse" field.</summary>
    public const int LeaveResponseFieldNumber = 3;
    private global::GameProtobufs.Services.LeaveResponse leaveResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtobufs.Services.LeaveResponse LeaveResponse {
      get { return leaveResponse_; }
      set {
        leaveResponse_ = value;
      }
    }

    /// <summary>Field number for the "updateResponse" field.</summary>
    public const int UpdateResponseFieldNumber = 4;
    private global::GameProtobufs.Services.UpdateResponse updateResponse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtobufs.Services.UpdateResponse UpdateResponse {
      get { return updateResponse_; }
      set {
        updateResponse_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResponseMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResponseMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ServiceType != other.ServiceType) return false;
      if (!object.Equals(JoinResponse, other.JoinResponse)) return false;
      if (!object.Equals(LeaveResponse, other.LeaveResponse)) return false;
      if (!object.Equals(UpdateResponse, other.UpdateResponse)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ServiceType != global::GameProtobufs.Services.ServiceTypes.Null) hash ^= ServiceType.GetHashCode();
      if (joinResponse_ != null) hash ^= JoinResponse.GetHashCode();
      if (leaveResponse_ != null) hash ^= LeaveResponse.GetHashCode();
      if (updateResponse_ != null) hash ^= UpdateResponse.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ServiceType != global::GameProtobufs.Services.ServiceTypes.Null) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ServiceType);
      }
      if (joinResponse_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(JoinResponse);
      }
      if (leaveResponse_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(LeaveResponse);
      }
      if (updateResponse_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(UpdateResponse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ServiceType != global::GameProtobufs.Services.ServiceTypes.Null) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ServiceType);
      }
      if (joinResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(JoinResponse);
      }
      if (leaveResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LeaveResponse);
      }
      if (updateResponse_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdateResponse);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResponseMessage other) {
      if (other == null) {
        return;
      }
      if (other.ServiceType != global::GameProtobufs.Services.ServiceTypes.Null) {
        ServiceType = other.ServiceType;
      }
      if (other.joinResponse_ != null) {
        if (joinResponse_ == null) {
          JoinResponse = new global::GameProtobufs.Services.JoinResponse();
        }
        JoinResponse.MergeFrom(other.JoinResponse);
      }
      if (other.leaveResponse_ != null) {
        if (leaveResponse_ == null) {
          LeaveResponse = new global::GameProtobufs.Services.LeaveResponse();
        }
        LeaveResponse.MergeFrom(other.LeaveResponse);
      }
      if (other.updateResponse_ != null) {
        if (updateResponse_ == null) {
          UpdateResponse = new global::GameProtobufs.Services.UpdateResponse();
        }
        UpdateResponse.MergeFrom(other.UpdateResponse);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ServiceType = (global::GameProtobufs.Services.ServiceTypes) input.ReadEnum();
            break;
          }
          case 18: {
            if (joinResponse_ == null) {
              JoinResponse = new global::GameProtobufs.Services.JoinResponse();
            }
            input.ReadMessage(JoinResponse);
            break;
          }
          case 26: {
            if (leaveResponse_ == null) {
              LeaveResponse = new global::GameProtobufs.Services.LeaveResponse();
            }
            input.ReadMessage(LeaveResponse);
            break;
          }
          case 34: {
            if (updateResponse_ == null) {
              UpdateResponse = new global::GameProtobufs.Services.UpdateResponse();
            }
            input.ReadMessage(UpdateResponse);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
